Translate documentation to 🇬🇧
europace/kex-vorgang-export-api pull request #38
Opened 2021-12-17 10:36 UTC by huehnerlady

2021-12-17 10:59 UTC, s-gurevich commented on README.md
> -Die angeforderten Daten werden ebenfalls als JSON übermittelt.
Dieser Abschnitt fehlt?

2021-12-17 11:00 UTC, huehnerlady commented on README.md
> -Die angeforderten Daten werden ebenfalls als JSON übermittelt.
das wird im neuen Abschnitt `GraphQL Requests` erklärt, daher habe ich es hier rausgenommen. Ich hatte dies analog zu kex-vorgang-update eingebaut

2021-12-17 11:01 UTC, huehnerlady commented on README.md
> -Die angeforderten Daten werden ebenfalls als JSON übermittelt.
AAchso und der andere Teil (wie die URL) ist weiter oben unter `General` gewandert

2021-12-17 12:00 UTC, HungryHarry requested changes
🇬🇧

2021-12-17 12:24 UTC, huehnerlady commented on README.md
> +| privatkredit:vorgang:lesel | KreditSmart-Vorgänge lesen | Scope for reading data of a Vorgang |
ne ich dachte "das kann ich auch tippen" 🤣

2021-12-17 13:30 UTC, HungryHarry approved these changes
🇬🇧

2021-12-17 13:30 UTC, HungryHarry commented on README.md
> +The Europace 2 PartnerID has 5-characters and has the format ABC12.
Hier nur kurz: Die PartnerID beschreiben wir an anderer Stelle als "This type is a 5-digit String and identifies PartnerID" 
Können wir hier so lassen (mit Bindestrich bin ich mir da nur nicht sicher) - stört mich so jetzt nicht, wollte es nur erwähnt haben.

2021-12-20 07:36 UTC, huehnerlady commented on README.md
> +The Europace 2 PartnerID has 5-characters and has the format ABC12.
hmmm wo denn?

Ich habe dies aus dem [import](https://github.com/europace/kex-vorgang-import-api#partner) kopiert 🤔

2021-12-20 07:40 UTC, HungryHarry commented on README.md
> +The Europace 2 PartnerID has 5-characters and has the format ABC12.
https://docs.api.europace.de/privatkredit/angebote/kex-angebote-api/#partner-id

Da, halt ein anderer Satzbau wohlgemerkt :) ​Und wenns an anderer Stelle schon so steht, dann wurde es ja auch so schon approved und passt dann für mich 👍

2021-12-20 08:02 UTC, huehnerlady commented on README.md
> +The Europace 2 PartnerID has 5-characters and has the format ABC12.
da könnte man im Zusammenhang mit dem aufhübschen drüber sprechen, also dass man solche Dinge auch vereinheitlicht :)

2021-12-20 08:02 UTC, merged